version: 3

output: prefixed
set: [errexit, nounset, pipefail]

vars:
  ALPINE: 3.24.1
  NEXTCLOUD: 34.0.2-apache

tasks:
  build:
    deps:
      - pgbouncer-build
      - restic-build
      - restic-pg-build
      - nextcloud-build
  publish:
    deps:
      - pgbouncer-publish
      - restic-publish
      - restic-pg-publish
      - nextcloud-publish

  pgbouncer-build:
    cmds:
      - task: build-container
        vars:
          NAME: pgbouncer

  pgbouncer-publish:
    cmds:
      - task: publish-container
        vars:
          NAME: pgbouncer

  restic-build:
    cmds:
      - task: build-container
        vars:
          NAME: restic
  restic-publish:
    cmds:
      - task: publish-container
        vars:
          NAME: restic

  restic-pg-build:
    deps:
      - restic-build
    cmds:
      - task: build-container
        vars:
          NAME: restic-pg
  restic-pg-publish:
    deps:
      - restic-publish
    cmds:
      - task: build-container
        vars:
          NAME: restic-pg

  nextcloud-build:
    cmds:
      - task: build-container
        vars:
          NAME: nextcloud
  nextcloud-publish:
    cmds:
      - task: build-container
        vars:
          NAME: nextcloud

  build-container:
    internal: true
    requires:
      vars:
        - NAME
    vars:
      TAG:
        sh: ./scripts/tag.sh ./{{ .NAME }}/Containerfile
    cmd: ./scripts/build.sh ./{{ .NAME }}/ docker.io/joshuachp/{{ .NAME }}:{{ .TAG }}

  publish-container:
    internal: true
    requires:
      vars:
        - NAME
    vars:
      TAG:
        sh: ./scripts/tag.sh ./{{ .NAME }}/Containerfile
    cmd: podman push docker.io/joshuachp/{{ .NAME }}:{{ .TAG }}
