version: 3

output: prefixed
set: [errexit, nounset, pipefail]

vars:
  ALPINE: 3.24.1
  NEXTCLOUD: 34.0.2-apache

tasks:
  build:
    deps:
      - pgbouncer-build
      - restic-build
      - nextcloud-build
      - restic-pg-build

  publish:
    deps:
      - pgbouncer-publish
      - restic-publish
      - restic-pg-publish
      - nextcloud-publish

  pgbouncer-build:
    cmds:
      - task: build-container
        vars:
          NAME: pgbouncer
  pgbouncer-publish:
    deps:
      - pgbouncer-build
    cmds:
      - task: publish-container
        vars:
          NAME: pgbouncer

  restic-build:
    cmds:
      - task: build-container
        vars:
          NAME: restic
  restic-publish:
    deps:
      - restic-build
    cmds:
      - task: publish-container
        vars:
          NAME: restic

  restic-pg-build:
    deps:
      - restic-build
    cmds:
      - task: build-container
        vars:
          NAME: restic-pg
  restic-pg-publish:
    deps:
      - restic-pg-build
    cmds:
      - task: publish-container
        vars:
          NAME: restic-pg

  nextcloud-build:
    cmds:
      - task: build-container
        vars:
          NAME: nextcloud
  nextcloud-publish:
    deps:
      - nextcloud-build
    cmds:
      - task: publish-container
        vars:
          NAME: nextcloud

  build-container:
    prefix: "build-{{ .NAME }}"
    internal: true
    requires:
      vars:
        - NAME
    vars:
      TAG:
        sh: ./scripts/tag.sh ./{{ .NAME }}/Containerfile
    cmd: ./scripts/build.sh {{ .NAME }} {{ .TAG }}

  publish-container:
    prefix: "publish-{{ .NAME }}"
    internal: true
    requires:
      vars:
        - NAME
    vars:
      TAG:
        sh: ./scripts/tag.sh ./{{ .NAME }}/Containerfile
    cmd: ./scripts/push.sh {{ .NAME }} {{ .TAG }}
