FROM --platform=$TARGETPLATFORM docker.io/library/nextcloud:35.0.0-apache

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg && \
    rm -rf /var/lib/apt/lists/*
